"""empty message

Revision ID: 604ec9a68ff5
Revises: 6545d5b5ddb1
Create Date: 2020-05-28 00:44:43.530167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604ec9a68ff5'
down_revision = '6545d5b5ddb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('test', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
